CREATE TABLE cargo (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(45) NOT NULL,
descricao VARCHAR(45) NOT NULL
);

CREATE TABLE endereco (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
cep VARCHAR(9) NOT NULL,
logradouro VARCHAR(120) NOT NULL,
bairro VARCHAR(80) NOT NULL,
cidade VARCHAR(80) NOT NULL,
uf VARCHAR(2) NOT NULL,
numero VARCHAR(10) NOT NULL,
complemento VARCHAR(60)
);

CREATE TABLE usuario (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(120) NOT NULL,
telefone VARCHAR(20) NOT NULL,
email VARCHAR(120) NOT NULL,
senha VARCHAR(255) NOT NULL,
data_nascimento DATE NOT NULL,
ativo BOOLEAN DEFAULT TRUE,
fkEndereco INT NOT NULL,
CONSTRAINT email_unique UNIQUE (email),
CONSTRAINT fk_usuario_endereco FOREIGN KEY (fkEndereco) REFERENCES endereco(id)
);

CREATE TABLE funcionario (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
fkUsuario INT NOT NULL,
fkCargo INT NOT NULL,
CONSTRAINT fk_funcionario_usuario FOREIGN KEY (fkUsuario) REFERENCES usuario(id) ON DELETE CASCADE,
CONSTRAINT fk_funcionario_cargo FOREIGN KEY (fkCargo) REFERENCES cargo(id)
);

CREATE TABLE agenda_excecao (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
fkFuncionario INT NOT NULL,
data DATE NOT NULL,
hora_inicio TIME,
hora_fim TIME,
disponivel BOOLEAN DEFAULT TRUE,
CONSTRAINT fk_agenda_excecao_funcionario FOREIGN KEY (fkFuncionario) REFERENCES funcionario(id) ON DELETE CASCADE
);

CREATE TABLE agenda_funcionario (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
fkFuncionario INT NOT NULL,
dia_semana INT NOT NULL,
hora_inicio TIME NOT NULL,
hora_fim TIME NOT NULL,
CONSTRAINT fk_agenda_funcionario FOREIGN KEY (fkFuncionario) REFERENCES funcionario(id) ON DELETE CASCADE
);

CREATE TABLE cliente (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
fkUsuario INT NOT NULL,
observacao VARCHAR(255),
CONSTRAINT fk_cliente_usuario FOREIGN KEY (fkUsuario) REFERENCES usuario(id) ON DELETE CASCADE
);

CREATE TABLE sala (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
descricao VARCHAR(45)
);

CREATE TABLE servico (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
valor DECIMAL(10,2) NOT NULL,
descricao VARCHAR(255) NOT NULL,
tempoMedio INT
);

CREATE TABLE status (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(45) NOT NULL
);

CREATE TABLE agendamento (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
data_hora_inicio TIMESTAMP NOT NULL,
data_hora_fim TIMESTAMP NOT NULL,
observacao VARCHAR(255),
fkCliente INT NOT NULL,
fkFuncionario INT NOT NULL,
fkSala INT NOT NULL,
fkServico INT NOT NULL,
fkStatus INT NOT NULL,
CONSTRAINT fk_ag_cliente FOREIGN KEY (fkCliente) REFERENCES cliente(id),
CONSTRAINT fk_ag_funcionario FOREIGN KEY (fkFuncionario) REFERENCES funcionario(id),
CONSTRAINT fk_ag_sala FOREIGN KEY (fkSala) REFERENCES sala(id),
CONSTRAINT fk_ag_servico FOREIGN KEY (fkServico) REFERENCES servico(id),
CONSTRAINT fk_ag_status FOREIGN KEY (fkStatus) REFERENCES status(id)
);

CREATE TABLE atendimento (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
fkAgendamento INT NOT NULL,
descricao VARCHAR(255),
observacoes VARCHAR(255),
CONSTRAINT fk_atendimento_agendamento FOREIGN KEY (fkAgendamento) REFERENCES agendamento(id) ON DELETE CASCADE
);

CREATE TABLE atendimento_servico (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
valor_unitario DECIMAL(10,2) NOT NULL,
fkAtendimento INT NOT NULL,
fkServico INT NOT NULL,
CONSTRAINT fk_at_servico_atendimento FOREIGN KEY (fkAtendimento) REFERENCES atendimento(id) ON DELETE CASCADE,
CONSTRAINT fk_at_servico_servico FOREIGN KEY (fkServico) REFERENCES servico(id)
);

CREATE TABLE especialidade (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(60) NOT NULL
);

CREATE TABLE especialidade_servico (
fkEspecialidade INT NOT NULL,
fkServico INT NOT NULL,
PRIMARY KEY (fkEspecialidade, fkServico),
CONSTRAINT fk_es_serv_especialidade FOREIGN KEY (fkEspecialidade) REFERENCES especialidade(id) ON DELETE CASCADE,
CONSTRAINT fk_es_serv_servico FOREIGN KEY (fkServico) REFERENCES servico(id) ON DELETE CASCADE
);

CREATE TABLE funcionario_especialidade (
fkFuncionario INT NOT NULL,
fkEspecialidade INT NOT NULL,
PRIMARY KEY (fkFuncionario, fkEspecialidade),
CONSTRAINT fk_func_es_funcionario FOREIGN KEY (fkFuncionario) REFERENCES funcionario(id) ON DELETE CASCADE,
CONSTRAINT fk_func_es_especialidade FOREIGN KEY (fkEspecialidade) REFERENCES especialidade(id) ON DELETE CASCADE
);

CREATE TABLE permissoes (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(45) NOT NULL,
descricao VARCHAR(45) NOT NULL
);

CREATE TABLE permissoes_cargo (
fkPermissoes INT NOT NULL,
fkCargo INT NOT NULL,
PRIMARY KEY (fkPermissoes, fkCargo),
CONSTRAINT fk_perm_cargo_perm FOREIGN KEY (fkPermissoes) REFERENCES permissoes(id) ON DELETE CASCADE,
CONSTRAINT fk_perm_cargo_cargo FOREIGN KEY (fkCargo) REFERENCES cargo(id) ON DELETE CASCADE
);

CREATE TABLE sala_servico (
fkSala INT NOT NULL,
fkServico INT NOT NULL,
PRIMARY KEY (fkSala, fkServico),
CONSTRAINT fk_sala_servico_sala FOREIGN KEY (fkSala) REFERENCES sala(id) ON DELETE CASCADE,
CONSTRAINT fk_sala_servico_servico FOREIGN KEY (fkServico) REFERENCES servico(id) ON DELETE CASCADE
);